
SELECT 
    A.AUTHOR_ID, B.AUTHOR_NAME, A.CATEGORY, SUM(COUNTER * PRICE) AS TOTAL_SALES
FROM 
    BOOK A 
    INNER JOIN AUTHOR B
    ON A.AUTHOR_ID = B.AUTHOR_ID
    INNER JOIN 
    (
    SELECT
        BOOK_ID, SUM(SALES) COUNTER
    FROM 
        BOOK_SALES A
    WHERE
        1=1
        AND TO_CHAR(TO_DATE(SALES_DATE, 'YYYY-MM-DD'),'MM') = '01'
    GROUP BY 
        BOOK_ID
    ) SALES
    ON A.BOOK_ID = SALES.BOOK_ID
GROUP BY    
    A.AUTHOR_ID, B.AUTHOR_NAME, CATEGORY
ORDER BY 
    A.AUTHOR_ID , CATEGORY DESC


-- ) D
-- WHERE 
--     D.MO = '01'
-- GROUP BY 
--     AUTHOR_NAME, CATEGORY
-- ORDER BY 
--     AUTHOR_ID ASC, AUTHOR_ID DESC