-- 코드를 입력하세요
SELECT
    EXTRACT(YEAR FROM SALES_DATE) YEAR,
    EXTRACT(MONTH FROM SALES_DATE) MONTH,
    GENDER,
    COUNT(DISTINCT B.USER_ID) USERS
FROM 
    USER_INFO A INNER JOIN ONLINE_SALE B
    ON A.USER_ID = B.USER_ID
WHERE 
    A.GENDER IS NOT NULL
GROUP BY 
    EXTRACT(YEAR FROM SALES_DATE), EXTRACT(MONTH FROM SALES_DATE), GENDER
ORDER BY 
    YEAR, MONTH, GENDER   

  