-- 코드를 입력하세요
SELECT 
    NAME, DATETIME
FROM 
(
    SELECT
        A.NAME, A.DATETIME
    FROM 
        ANIMAL_INS A LEFT JOIN ANIMAL_OUTS B
        ON A.ANIMAL_ID = B.ANIMAL_ID
    WHERE 
        1=1
        AND B.ANIMAL_ID IS NULL
    ORDER BY 
        A.DATETIME
)
WHERE
    1=1
    AND ROWNUM <= 3
ORDER BY 
    DATETIME