SELECT  DEV.ID,
        DEV.EMAIL,
        DEV.FIRST_NAME,
        DEV.LAST_NAME
FROM    DEVELOPERS AS DEV
WHERE   (DEV.SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#')) 
        OR
        (DEV.SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python')) 
ORDER BY DEV.ID ASC
