SELECT 
    SUM(FISH_COUNT) FISH_COUNT
FROM 
(
SELECT 
   A.FISH_TYPE, COUNT(FISH_NAME) FISH_COUNT
FROM 
    FISH_INFO A INNER JOIN FISH_NAME_INFO B
    ON A.FISH_TYPE = B.FISH_TYPE
WHERE 
    FISH_NAME IN ('BASS', 'SNAPPER')
GROUP BY 
    A.FISH_TYPE
) B