-- 코드를 입력하세요

-- SELECT UB.TITLE, UB.BOARD_ID, UR.REPLY_ID,UR.WRITER_ID, UR.CONTENTS, TO_CHAR(UR.CREATED_DATE,'YYYY-MM-DD') AS CREATED_DATE
--     FROM USED_GOODS_BOARD UB , USED_GOODS_REPLY UR
-- WHERE TO_CHAR(UB.CREATED_DATE,'YYYY-MM')='2022-10'AND UB.BOARD_ID = UR.BOARD_ID
-- ORDER BY UR.CREATED_DATE ASC , UB.TITLE ASC
-- ;

SELECT 
    B.TITLE, B.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS, TO_CHAR(R.CREATED_DATE, 'YYYY-MM-DD') CREATED_DATE
FROM 
    USED_GOODS_BOARD B, USED_GOODS_REPLY R
WHERE 
    TO_CHAR(B.CREATED_DATE, 'YYYY-MM') = '2022-10'
    AND B.BOARD_ID = R.BOARD_ID
ORDER BY  
    R.CREATED_DATE ASC, B.TITLE ASC