-- 코드를 작성해주세요
# SELECT * FROM HR_DEPARTMENT;
# SELECT * FROM HR_EMPLOYEES;

SELECT 
    A.DEPT_ID, A.DEPT_NAME_EN, ROUND(AVG(SAL)) AVG_SAL
FROM 
    HR_DEPARTMENT A,
    HR_EMPLOYEES B
WHERE 
    1=1
    AND A.DEPT_ID = B.DEPT_ID
GROUP BY 
    A.DEPT_ID, A.DEPT_NAME_EN
ORDER BY 
    AVG_SAL DESC
