-- 코드를 입력하세요
SELECT 
    A.CG CATEGORY, A.MP MAX_PRICE, B.PRODUCT_NAME PRODUCT_NAME
FROM
(
    SELECT CATEGORY CG, MAX(PRICE) MP
    FROM FOOD_PRODUCT 
    GROUP BY CATEGORY
) A INNER JOIN FOOD_PRODUCT B
ON A.MP = B.PRICE
AND A.CG = B.CATEGORY
WHERE 
    A.CG IN ('과자', '국', '김치', '식용유')
ORDER BY 
    A.MP DESC
    
